enum MatchStatuses {
  TIMED = 'TIMED',
  SCHEDULED = 'SCHEDULED',
  LIVE = 'LIVE',
  IN_PLAY = 'IN_PLAY',
  PAUSED = 'PAUSED',
  // EXTRA_TIME = 'EXTRA_TIME',
  // PENALTY_SHOOTOUT = 'PENALTY_SHOOTOUT',
  FINISHED = 'FINISHED',
  POSTPONED = 'POSTPONED',
  SUSPENDED = 'SUSPENDED',
  CANCELLED = 'CANCELLED',
  // AWARDED = 'AWARDED',
}
export { MatchStatuses };
